---
#- hosts: all
#- import_playbook: ../static_assignments/common_del.yml

#- hosts: all
#- import_playbook: ../static_assignments/common.yml

- hosts: uat_webservers
- import_playbook: ../static_assignments/uat_webservers.yml




